# Generated by Django 5.2 on 2025-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_auth_type_user_google_id_alter_place_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, choices=[('xinyi', 'Xinyi'), ('datong', 'Datong'), ('daan', "Da'an"), ('shilin', 'Shilin'), ('wanhua', 'Wanhua'), ('songshan', 'Songshan'), ('zhongshan', 'Zhongshan'), ('beitou', 'Beitou'), ('nangang', 'Nangang'), ('wenshan', 'Wenshan'), ('neihu', 'Neihu'), ('zhongzheng', 'Zhongzheng'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['slug'], name='core_place_slug_ef637d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['district'], name='core_place_distric_6da8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='core_place_latitud_c409b7_idx'),
        ),
    ]
