# Generated by Django 5.0.2 on 2025-05-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savedplace'),
        ('core', '0005_update_price_range_field'),
    ]

    operations = [
    ]
