# Generated by Django 5.2 on 2025-05-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_price_range_increments'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
