# Generated by Django 5.2 on 2025-05-14 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_photo_moderation_comment_place_moderation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('review_approved', 'Review Approved'), ('review_rejected', 'Review Rejected'), ('photo_approved', 'Photo Approved'), ('photo_rejected', 'Photo Rejected'), ('place_approved', 'Place Approved'), ('place_rejected', 'Place Rejected'), ('new_review', 'New Review'), ('new_photo', 'New Photo'), ('review_helpful', 'Review Helpful')], max_length=50),
        ),
        migrations.CreateModel(
            name='HelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_helpful', models.BooleanField(default=True, help_text='Whether the user found the review helpful')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='core.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SavedPlace',
        ),
        migrations.AddIndex(
            model_name='helpfulvote',
            index=models.Index(fields=['review', 'user'], name='core_helpfu_review__225559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='helpfulvote',
            unique_together={('review', 'user')},
        ),
    ]
