# Generated by Django 5.2 on 2025-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_review_helpful_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('amenity', 'Amenity'), ('cuisine', 'Cuisine'), ('atmosphere', 'Atmosphere'), ('service', 'Service Option'), ('payment', 'Payment Option'), ('accessibility', 'Accessibility'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('name', 'type')},
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['type'], name='core_featur_type_602217_idx'),
        ),
    ]
