# Generated by Django 5.2 on 2025-05-14 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_feature_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', help_text="User's personal notes about this place")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='core_savedp_user_id_fcf9ed_idx'), models.Index(fields=['place'], name='core_savedp_place_i_991228_idx'), models.Index(fields=['created_at'], name='core_savedp_created_1a7647_idx')],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
