# Generated by Django 5.0.2 on 2025-05-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_place_fields'),
        ('core', '0015_alter_notification_notification_type_badge_userbadge_and_more'),
    ]

    operations = [
    ]
