# Generated by Django 5.0.2 on 2025-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250519_2234'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='place',
            name='core_place_type_de8a3c_idx',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='place_type',
        ),
        migrations.AlterField(
            model_name='photo',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_range',
            field=models.CharField(choices=[(0, 'Free'), (200, 'NT$1-200'), (400, 'NT$200-400'), (600, 'NT$400-600'), (800, 'NT$600-800'), (1000, 'NT$800-1000'), (1500, 'NT$1000-1500'), (2000, 'NT$1500-2000'), (3000, 'NT$2000+')], help_text='Price range in NT$ (0=Free, 200=NT$1-200, 400=NT$200-400, 600=NT$400-600, 800=NT$600-800, 1000=NT$800-1000, 1500=NT$1000-1500, 2000=NT$1500-2000, 2000+=NT$2000+)', max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['place_type'], name='core_place_place_t_e7bd09_idx'),
        ),
    ]
