# Generated by Django 5.0.2 on 2025-05-21 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_place_core_place_type_de8a3c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='user',
        ),
        migrations.AddField(
            model_name='place',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
