# Generated by Django 5.0.2 on 2025-05-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fix_model_alignments'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['created_by'], name='core_place_contrib_f5be66_idx'),
        ),
    ]
