# Generated by Django 5.0.2 on 2025-05-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_created_by_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='core_place_created_f55503_idx',
            old_name='core_place_contrib_f5be66_idx',
        ),
        migrations.RemoveField(
            model_name='place',
            name='average_cleanliness_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='average_food_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='average_service_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='average_value_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='contributor',
        ),
        migrations.AddField(
            model_name='place',
            name='contributor_id',
            field=models.CharField(default='default_user', max_length=128),
            preserve_default=False,
        ),
    ]
