# Generated by Django 5.0.2 on 2025-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_core_place_contrib_f5be66_idx_core_place_created_f55503_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['feature_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='placephoto',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveIndex(
            model_name='feature',
            name='core_featur_feature_5f6998_idx',
        ),
        migrations.RemoveIndex(
            model_name='placephoto',
            name='core_placep_isPrima_b5d73a_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='core_review_helpful_09695d_idx',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='maxLevel',
            new_name='max_level',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='featureType',
            new_name='feature_type',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='price_range',
            new_name='price_level',
        ),
        migrations.RenameField(
            model_name='placephoto',
            old_name='isApproved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='placephoto',
            old_name='isPrimary',
            new_name='is_primary',
        ),
        migrations.RenameField(
            model_name='placephoto',
            old_name='uploadedAt',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='foodQuality',
            new_name='food_quality',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='helpfulCount',
            new_name='helpful_count',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='overallRating',
            new_name='overall_rating',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='guideLevel',
            new_name='guide_level',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='guidePoints',
            new_name='guide_points',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='earnedAt',
            new_name='earned_at',
        ),
        migrations.AlterField(
            model_name='place',
            name='contributor_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['feature_type'], name='core_featur_feature_8aec5c_idx'),
        ),
        migrations.AddIndex(
            model_name='placephoto',
            index=models.Index(fields=['is_primary'], name='core_placep_is_prim_e1f91b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['helpful_count'], name='core_review_helpful_0b7785_idx'),
        ),
    ]
