# Generated by Django 5.2 on 2025-05-22 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_feature_options_alter_placephoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
    ]
