# Generated by Django 5.2 on 2025-05-22 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_feature_options_alter_feature_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placefeature',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False),
        ),
    ]
